from turtle import *
screensize(2000, 2000)
def lil_circle(x, y):
    down()
    begin_fill()
    goto(x, y)
    circle(15)
    fillcolor('grey')
    end_fill()
    up()
def big_circle(x, y):
    down()
    begin_fill()
    goto(x,y)
    circle(50)
    fillcolor('green')
    end_fill()
    up()
def paralelogram(x, y):
    down()
    begin_fill()
    goto(x,y)
    fillcolor('turquoise')
    lt(90)
    fd(50)
    lt(45)
    fd(50)
    lt(135)
    fd(50)
    lt(45)
    fd(50)
    lt(45)
    end_fill()
    up()
print(привет семе)
